services:
  mitzu-webapp:
    image: imeszaros/mitzu-webapp:latest
    restart: always
    entrypoint: gunicorn -b 0.0.0.0:80 --workers=2 app:server 
    environment:
      BASEPATH: /var/task/basepath/      
      HOME_URL: http://localhost:8082/
      NOT_FOUND_URL: http://localhost:8082/not_found      
    ports:
      - 8082:80
    volumes:
      - ./mitzu/:/var/task/basepath/
