version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mitzu-demo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rvy2n6csufge"
s3_prefix = "mitzu-demo-app"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["MitzuDemoApp=531968921201.dkr.ecr.eu-west-1.amazonaws.com/mitzudemoapp3e0505f7/mitzudemoapp5db9f81arepo"]
