services:
  mitzu-webapp:
    image: mitzuio/mitzu:snapshot
    restart: always
    entrypoint: gunicorn -b 0.0.0.0:8080 --workers=2 app:server
    environment:
      STORAGE_REDIS_HOST: "localhost"
      STORAGE_REDIS_PORT: 6379
    ports:
      - 8082:8080
    depends_on:
      - storage
    volumes:
      - ./data/cache:./cache

  storage:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
