networks:
  main:
services:
  mitzu-webapp:
    image: mitzuio/mitzu:latest
    restart: always
    environment:
      STORAGE_REDIS_HOST: "storage"
      STORAGE_REDIS_PORT: 6379
      SETUP_SAMPLE_PROJECT: "true"
    ports:
      - 8082:8080
    depends_on:
      - storage
    networks:
      - main

  storage:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    networks:
      - main
