name: Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install poetry dependencies
        run: |
          poetry install -E trinodwh -E mysql -E postgres
      - name: Start docker images
        uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "tests/integration/docker/docker-compose.yml"
      - name: Waiting for trino server
        run: |
          cat <<"RUBY" | ruby
          30.times do
            exit if `curl http://localhost:8080/v1/info 2>/dev/null | jq .starting`.strip == 'false'
            puts "Trino is not yet ready, waiting 2 seconds then retrying ..."
            sleep 2
          end
          exit!
          RUBY
          curl http://localhost:8080/v1/info 2>/dev/null | jq
      - name: Setup trino test data
        run: |
          make trino_setup_test_data
      - name: Check
        run: |
          make check_ci
      - name: Dump trino logs
        if: failure()
        run: |
          curl http://localhost:8080/v1/info 2>/dev/null | jq
          docker logs docker_trino-coordinator_1
      - name: Collect coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          output: both
      - name: Comment coverage report
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
