name: Check
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install poetry dependencies
        run: |
          make init
      - name: Start docker images
        uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "docker/docker-compose.yml"
      - name: Waiting for trino server
        run: |
          poetry run python3 scripts/wait_for_trino.py
      - name: Setup trino test data
        run: |
          make trino_setup_test_data
      - name: Testing and validation
        run: |
          make check
      - name: Dump trino logs
        if: failure()
        run: |
          curl http://localhost:8080/v1/info 2>/dev/null | jq
          docker logs docker-trino-coordinator-1
      - name: Collect coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          output: both
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Comment coverage report
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
