name: Release Mitzu
on:
  release:
    types: [published]

jobs:
  publish_pypi_package:
    name: Publish Pypi package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install poetry dependencies
        run: |
          make init
      - name: Set semantic version
        run: |
          poetry dynamic-versioning
      - name: Poetry build
        run: |
          poetry build
      - name: Publish to Pypi
        run: |
          poetry publish -u '${{ secrets.PYPI_USERNAME }}' -p '${{ secrets.PYPI_PASSWORD }}'

  publish_docker_image:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install poetry dependencies
        run: |
          make init
      - name: Set semantic version
        run: |
          poetry dynamic-versioning
      - name: Build and publish docker
        run: |
          docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}' docker.io
          make docker_build_latest
          docker push mitzuio/mitzu:$(poetry version -s)
          docker push mitzuio/mitzu:latest
